require "keymaps"
require "options"
require "lazy-config"
require "git-config"
require "lualine-config"
--require "bufferline-config"
require "lsp-config"
require "nvim-tree-config"
require "fzf-lua-config"
require("copilot-config")
